---
- name: Install default package for k8s_hosts
  hosts: k8s_hosts
  vars_files:
    - ../group_vars/k8s_hosts.yml
  become: true
  tasks:
    - name: Add local DNS [OPTIONAL]
      ansible.builtin.template:
        src: ../templates/dns_local/hosts.j2
        dest: /etc/cloud/templates/hosts.debian.tmpl
        owner: root
        group: root
        mode: "0644"
      notify: reboot_vm 

    - name: Update system package index before installing kubes commands
      ansible.builtin.apt:
        update_cache: true

    - name: install requirement installation tools
      ansible.builtin.apt:
        name: "{{ lookup('file', '../files/apt/lists/requirement_k8s_installation.list').splitlines() }}"
        state: present

    - name: Check / Create apt keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download public signing key for kubernetes package repository
      ansible.builtin.get_url:
        url: "https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key"
        dest: "/tmp/Release.key"
        mode: "0755"
        owner: root
        group: root
        timeout: 30

    - name: dearmor key for the apt keyring
      ansible.builtin.command:
        cmd: /usr/bin/gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key

    - name: Add kubernetes repository [pkgs.k8s.io]
      ansible.builtin.copy:
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ /\n"
        dest: /etc/apt/sources.list.d/kubernetes.list
        owner: root
        group: root
        mode: "0644"

    - name: Force packages version for kubes commands
      ansible.builtin.copy:
        src: ../files/apt/preferences.d/kube_cmd_version
        dest: /etc/apt/preferences.d/kube_cmd_version
        owner: root
        group: root
        mode: '0644'

    - name: Installation of kubes binary
      ansible.builtin.apt:
        name: "{{ lookup('file', '../files/apt/lists/kube_cmd.list').split('\n') }}"
        state: present
        update_cache: true

    - name: Enable ip_forward for the kernel
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: "net.ipv4.ip_forward = 1\n"
        owner: root
        group: root
        mode: "0644"
      notify: reload_sysctl

    - name: Configure CgroupDriver
      block:
        - name: Ensure /var/lib/kubelet exist
          ansible.builtin.file:
            path: /var/lib/kubelet
            state: directory
            owner: root
            group: root
            mode: "0750"

        - name: Set kubelet with systemd cgroup manager
          ansible.builtin.copy:
            src: ../files/var/lib/kubelet/config.yaml
            dest: /var/lib/kubelet/config.yaml
            owner: root
            group: root
            mode: "0644"
          notify: restart_kubelet

        - name: Set containerd with systemd cgroup manager
          ansible.builtin.copy:
            src: ../files/containerd/config.toml
            dest: /etc/containerd/config.toml
            owner: root
            group: root
            mode: "0644"
          notify: restart_containerd
       
    - name: Start and Enable kubelet service
      ansible.builtin.systemd_service:
        name: kubelet
        state: started
        enabled: true

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Show kubelet status
      ansible.builtin.debug:
        msg:
          enabled:      "{{ ansible_facts.services['kubelet.service'].status }}"
          active_state: "{{ ansible_facts.services['kubelet.service'].state }}"

  handlers:
        - name: reboot_vm 
          ansible.builtin.reboot:
            msg: "Initialyze {{ inventory_hostname }}"

        - name: restart_kubelet
          ansible.builtin.systemd_service:
            name: kubelet
            state: restarted
            daemon_reload: true

        - name: restart_containerd
          ansible.builtin.systemd_service:
            name: containerd
            state: restarted
            daemon_reload: true
       
        - name: reload_sysctl
          ansible.builtin.command:
            cmd: sysctl --system

