---
- name: Configure cri tool and cgroup manager for kubelet and containerd
  hosts: k8s_hosts
  vars_files:
    - ../group_vars/k8s_hosts.yml
  become: true
  tasks:
    - name: Configure CgroupDriver
      block:
        - name: Ensure /var/lib/kubelet exist
          ansible.builtin.file:
            path: /var/lib/kubelet
            state: directory
            owner: root
            group: root
            mode: "0750"

        - name: Set kubelet with systemd cgroup manager
          ansible.builtin.copy:
            src: ../files/var/lib/kubelet/config.yaml
            dest: /var/lib/kubelet/config.yaml
            owner: root
            group: root
            mode: "0644"
          notify: restart_kubelet

        - name: Set containerd with systemd cgroup manager
          ansible.builtin.copy:
            src: ../files/containerd/config.toml
            dest: /etc/containerd/config.toml
            owner: root
            group: root
            mode: "0644"
          notify: restart_containerd
       
    - name: Start and Enable kubelet service
      ansible.builtin.systemd_service:
        name: kubelet
        state: started
        enabled: true

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Show kubelet status
      ansible.builtin.debug:
        msg:
          enabled:      "{{ ansible_facts.services['kubelet.service'].status }}"
          active_state: "{{ ansible_facts.services['kubelet.service'].state }}"

    - name: Install crictl configuration
      ansible.builtin.copy:
        src: ../files/cri/crictl.yaml
        dest: /etc/crictl.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Show cri including stopped contianers
      block:
        - name: Exec crictl
          ansible.builtin.command:
            cmd: crictl ps -a
          register: return_crictl

        - name: Show command return
          ansible.builtin.debug:
            msg: "{{ return_crictl.stdout }}"

  handlers:
    - name: restart_kubelet
      ansible.builtin.systemd_service:
        name: kubelet
        state: restarted
        daemon_reload: true

    - name: restart_containerd
      ansible.builtin.systemd_service:
        name: containerd
        state: restarted
        daemon_reload: true
    
