---
- name: Bootstrap du cluster
  hosts: k8s_init_master
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/k8s_hosts.yml
    - ../group_vars/k8s_init_master.yml
  become: true
  tasks:   
    - name: init master 
      ansible.builtin.command:
        argv:
          - kubeadm 
          - init
          - "--control-plane-endpoint={{ hostvars[groups['loadbalancers'][0]]['ansible_host'] }}:{{ api_server_src_port }}"
          - "--upload-certs"
          - "--kubernetes-version={{ kubernetes_version }}"
          - "--pod-network-cidr={{ pods_network_cidr }}"
        creates: /etc/kubernetes/admin.conf
      register: init_first_master

    - name: Show init logs
      ansible.builtin.debug:
        msg: "{{ init_first_master.stdout_lines }}"
              

    - name: Extract join token and cert hash
      ansible.builtin.set_fact:
        join_token: "{{ init_first_master.stdout | regex_search('--token ([a-z0-9]+\\.[a-z0-9]+)', '\\1') | first }}"
        join_cert_hash: "{{ init_first_master.stdout | regex_search('--discovery-token-ca-cert-hash (sha256:[a-f0-9]+)', '\\1') | first }}"
        join_certificate_key: "{{ init_first_master.stdout | regex_search('--certificate-key ([a-f0-9]+)', '\\1') | first }}"

    - name: Show parsed values
      ansible.builtin.debug:
        msg:
          token:           "{{ join_token }}"
          cert_hash:       "{{ join_cert_hash }}"
          certificate_key: "{{ join_certificate_key }}"

    - name: Persist join values for use in join playbook
      ansible.builtin.copy:
        content: |
          token:            "{{ join_token }}"
          cert_hash:        "{{ join_cert_hash }}"
          certificate_key:  "{{ join_certificate_key }}"
        dest: "../vars/k8s_join_vars.yml"
      delegate_to: localhost
      become: false
      run_once: true

    - name: Check / Create kubernetes calico directory
      ansible.builtin.file:
        path: /etc/kubernetes/calico
        state: directory
        mode: '0755'

    - name: Add calico plugin self-configured yaml
      ansible.builtin.copy:
        src: ../files/calico/calico.yaml
        dest: /etc/kubernetes/calico/calico.yaml
    
    - name: Apply Calico manifest
      ansible.builtin.command:
        cmd: kubectl apply -f /etc/kubernetes/calico/calico.yaml
      register: calico_install

    - name: Show calico install
      ansible.builtin.debug:
        msg: "{{ calico_install }}"

    - name: Wait for first master to be Ready
      ansible.builtin.command:
        argv:
          - kubectl 
          - wait 
          - "--for=condition=Ready"
          - "node/{{ hostvars[groups['k8s_init_master'][0]]['ansible_hostname'] }}{{ domain }}"
          - "--timeout=300s"
      register: wait_result

    - name: Show parsed values
      ansible.builtin.debug:
        msg: "{{ wait_result }}"

