all:
  children:
    app_host:
      hosts:
        app-vm-01:
          ansible_host: 192.168.1.101
        app-vm-02:
          ansible_host: 192.168.1.102
        app-vm-03:
          ansible_host: 192.168.1.103

    db_host:
      hosts:
        db-vm-01:
          ansible_host: 192.168.1.111
        db-vm-02:
          ansible_host: 192.168.1.112
        db-vm-03:
          ansible_host: 192.168.1.113

    elastic_host:
      children:
        db_host:
        app_host:
