---
cluster_name: "auto_deploy_cluster"
cluster_uuid: "null"

discovery_seed_hosts: >-
  [{% for host in groups['db_hosts'] %}
  "{{ hostvars[host]['ansible_host'] }}:9300"
  {% if not loop.last %},
  {% endif %}
  {% endfor %}]

node_roles:
  - "master"
  - "data"
  - "ingest"

cluster_initial_master_nodes: >-
  [{% for host in groups['db_hosts'] %}
  "{{ host }}"
  {% if not loop.last %},
  {% endif %}
  {% endfor %}]

elastic_certs: "/etc/elasticsearch/certs/"
elastic_bin: "/usr/share/elasticsearch/bin"
ca_stack_p12: "{{ elastic_certs }}/elastic-stack-ca.p12"
cert_host_p12: "{{ elastic_certs }}/elastic-certificates.p12"
