---
- name: Delete kubernetes cluster
  hosts: k8s_hosts
  become: true
  tasks:
    - name: kubeadm reset
      ansible.builtin.command:
        cmd: kubeadm reset -f
      ignore_errors: true

    - name: Remove kubernetes directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/etcd
        - /var/lib/kubelet
        - /var/lib/kubeadm
        - /etc/cni
        - /opt/cni
        - /var/lib/cni
        - /run/flannel
        - /root/.kube

    - name: Flush iptables
      ansible.builtin.shell: |
        iptables -F
        iptables -X
        iptables -t nat -F
        iptables -t nat -X
        iptables -t mangle -F
        iptables -t mangle -X
      ignore_errors: true

    - name: Remove virtual network interfaces
      ansible.builtin.shell: |
        ip link delete flannel.1 2>/dev/null || true
        ip link delete cni0 2>/dev/null || true
        ip link delete tunl0 2>/dev/null || true
      ignore_errors: true
    
    - name: Clear containerd
      ansible.builtin.shell: |
        for mp in $(mount | grep '/run/containerd/' | awk '{print $3}'); do   umount -l "$mp"; done
        for mp in $(mount | grep '/var/lib/kubelet/pods' | awk '{print $3}'); do   umount -l "$mp"; done
        for mp in $(mount | grep '/run/containerd/io.containerd.runtime.v2.task' | awk '{print $3}'); do   umount -l "$mp"; done
      ignore_errors: true

    - name: Stop kubelet
      ansible.builtin.systemd_service:
        name: kubelet
        state: stopped
      ignore_errors: true

    - name: Restart containerd
      ansible.builtin.systemd_service:
        name: containerd
        state: restarted
