---
- name: APT update and minimal install
  hosts: all
  vars_files:
    - ../group_vars/all.yml
  become: true
  tasks:
    - name: Force debian 12 repositoty
      #if not use cloud-init default mirror
      ansible.builtin.copy:
        src: ../files/apt/sources.list.d/debian12.list
        dest: /etc/apt/sources.list.d/debian12.list

    - name: Update debian
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade full debian
      ansible.builtin.apt:
        upgrade: full

    - name: Install minimal list of packages
      ansible.builtin.apt:
        name: "{{ lookup('file', '../files/apt/lists/default.server.list').split('\n') }}"
        state: present
        update_cache: true
          
    - name: Disable cloud-init manage_etc_hosts
      #if you don't wan t to use cloud-init template
      ansible.builtin.lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^manage_etc_hosts'
        line: 'manage_etc_hosts: false'
        state: present
          
    - name: Replace hosts file
      ansible.builtin.template:
        src: ../templates/etc_files/hosts.yml.j2
        dest: /etc/hosts
        mode: '0644'
        owner: root
        group: root

    - name: Set FQDN hostname file
      ansible.builtin.template:
        src: ../templates/etc_files/hostname.yml.j2
        dest: /etc/hostname
        mode: '0644'
        owner: root
        group: root

    - name: Reboot machine to apply cloud configuration
      ansible.builtin.reboot:
        msg: "Initialyze {{ inventory_hostname }}"
